### ISSUE TITLE
how this help file can be used?

### ISSUE THREAD

**Issue by yanceyy** [Cocotteseb/Krypton#2]
i tried to install the help file in vs2010,but i failed...

**Comment by jacobmesu** [comment]
You could try the help file in this branch: https://github.com/ComponentFactory/Krypton/tree/2013

**Comment by Cocotteseb** [comment]
Hi, 

I wasn't able to install this help file since VS 2012. I've spent some hours to extract it and I've put it in a PDF format. It is available in the Help folder.
[https://github.com/Cocotteseb/Krypton/blob/master/Help/Krypton%20Suite%20Help.pdf](https://github.com/Cocotteseb/Krypton/blob/master/Help/Krypton%20Suite%20Help.pdf)
